apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-lake
  description: Componente Regenera do domínio lake.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-lake
  system: regenera-bank
