apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-product-catalog
  description: Componente Regenera do domínio product-catalog.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-product-catalog
  system: regenera-bank
