apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-regulatory-sisorf
  description: Componente Regenera do domínio sisorf.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-regulatory-sisorf
  system: regenera-bank
