apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-terraform
  description: Componente Regenera do domínio terraform.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-terraform
  system: regenera-bank
