apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-disaster-recovery
  description: Componente Regenera do domínio disaster-recovery.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-disaster-recovery
  system: regenera-bank
