apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-regulatory-cosif
  description: Componente Regenera do domínio cosif.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-regulatory-cosif
  system: regenera-bank
