apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-governance
  description: Componente Regenera do domínio governance.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-governance
  system: regenera-bank
