apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-loan-servicing
  description: Componente Regenera do domínio loan-servicing.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-loan-servicing
  system: regenera-bank
