apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-secrets
  description: Componente Regenera do domínio secrets.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-secrets
  system: regenera-bank
