apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-product-governance
  description: Componente Regenera do domínio product-governance.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-product-governance
  system: regenera-bank
