apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-tool-schema-validator
  description: Componente Regenera do domínio schema-validator.
  annotations:
    regenera.io/criticality: medium
spec:
  type: service
  lifecycle: experimental
  owner: team-developer-experience
  system: regenera-bank
