apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-regulatory-cybersecurity
  description: Componente Regenera do domínio cybersecurity.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-regulatory-cybersecurity
  system: regenera-bank
