apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-investment-orders
  description: Componente Regenera do domínio investment-orders.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-investment-orders
  system: regenera-bank
