apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-detection
  description: Componente Regenera do domínio detection.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-detection
  system: regenera-bank
