apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-mobile
  description: Componente Regenera do domínio mobile.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-mobile
  system: regenera-bank
