apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-control-case-management
  description: Componente Regenera do domínio case-management.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-case-management
  system: regenera-bank
