apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-engineering-governance
  description: Componente Regenera do domínio engineering-governance.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-engineering-governance
  system: regenera-bank
