apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-control-accounting
  description: Componente Regenera do domínio accounting.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-accounting
  system: regenera-bank
