apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-quality-e2e
  description: Componente Regenera do domínio e2e.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-quality
  system: regenera-bank
