apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-analytics
  description: Componente Regenera do domínio analytics.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-analytics
  system: regenera-bank
