package bank.regenera.transactions.domain.model

enum class TransactionState { CREATED, VALIDATING, RISK_ANALYSIS, AUTHORIZED, FUNDS_RESERVED, SENT, ACCEPTED, SETTLED, RECONCILED, REJECTED, CANCELLED, EXPIRED, REVERSED, UNKNOWN, MANUAL_REVIEW }
