apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-pam
  description: Componente Regenera do domínio pam.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-pam
  system: regenera-bank
