apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-pki
  description: Componente Regenera do domínio pki.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-pki
  system: regenera-bank
