apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-onboarding
  description: Componente Regenera do domínio onboarding.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-onboarding
  system: regenera-bank
