apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-iam
  description: Componente Regenera do domínio iam.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-iam
  system: regenera-bank
