apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-enterprise-architecture
  description: Componente Regenera do domínio architecture.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-architecture
  system: regenera-bank
