apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-red-team
  description: Componente Regenera do domínio red-team.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-red-team
  system: regenera-bank
