apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-fraud
  description: Componente Regenera do domínio fraud.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-fraud
  system: regenera-bank
