apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-streaming
  description: Componente Regenera do domínio streaming.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-streaming
  system: regenera-bank
