apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-treasury
  description: Componente Regenera do domínio treasury.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-treasury
  system: regenera-bank
