apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-custody-positions
  description: Componente Regenera do domínio custody-positions.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-custody-positions
  system: regenera-bank
