apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-invoices
  description: Componente Regenera do domínio invoices.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-invoices
  system: regenera-bank
