apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-cloud
  description: Componente Regenera do domínio cloud.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-cloud
  system: regenera-bank
