apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-integration-open-finance
  description: Componente Regenera do domínio open-finance.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-integration-open-finance
  system: regenera-bank
