apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-card-authorization
  description: Componente Regenera do domínio card-authorization.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-card-authorization
  system: regenera-bank
