apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-pix
  description: Componente Regenera do domínio pix.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-pix
  system: regenera-bank
