apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-fees
  description: Componente Regenera do domínio fees.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-fees
  system: regenera-bank
