apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-risk-models
  description: Componente Regenera do domínio risk-models.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-risk-models
  system: regenera-bank
