apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-event-bus
  description: Componente Regenera do domínio event-bus.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-event-bus
  system: regenera-bank
