apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-threat-intelligence
  description: Componente Regenera do domínio threat-intelligence.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-threat-intelligence
  system: regenera-bank
