apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-contracts-json-schema
  description: Componente Regenera do domínio json-schema.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-architecture
  system: regenera-bank
