apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-balance
  description: Componente Regenera do domínio balance.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-balance
  system: regenera-bank
