apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-risk-sanctions
  description: Componente Regenera do domínio sanctions.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-sanctions
  system: regenera-bank
