apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-ledger
  description: Componente Regenera do domínio ledger.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-ledger
  system: regenera-bank
