apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-iso20022-messages
  description: Componente Regenera do domínio iso20022-messages.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-payments
  system: regenera-bank
