apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-customers
  description: Componente Regenera do domínio customers.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-customers
  system: regenera-bank
