apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-regulatory-card-pci
  description: Componente Regenera do domínio card-pci.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-regulatory-card-pci
  system: regenera-bank
