apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-quality
  description: Componente Regenera do domínio quality.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-quality
  system: regenera-bank
