apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-risk-aml
  description: Componente Regenera do domínio aml.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-aml
  system: regenera-bank
