apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-fx
  description: Componente Regenera do domínio fx.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-fx
  system: regenera-bank
