apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-control-audit
  description: Componente Regenera do domínio audit.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-audit
  system: regenera-bank
