apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-disputes
  description: Componente Regenera do domínio disputes.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-disputes
  system: regenera-bank
