apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-noc
  description: Componente Regenera do domínio noc.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-noc
  system: regenera-bank
