apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-credit-origination
  description: Componente Regenera do domínio credit-origination.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-credit-origination
  system: regenera-bank
