# [FILE] /Users/admin/Desktop/Regenera Bank Documents/IaC & Security/kubernetes/service-mesh/mesh-peer-authentication.yaml
# Istio PeerAuthentication Policy for enforcing mTLS
# Desenvolvedor: Don Paulo Ricardo

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-mtls-strict # Nome da política
  namespace: default        # Aplica-se ao namespace 'default', ajustar conforme necessário
spec:
  mtls:
    mode: STRICT # Força o mTLS para todo o tráfego dentro do namespace
