apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-accounts
  description: Componente Regenera do domínio accounts.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-accounts
  system: regenera-bank
