apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-notifications
  description: Componente Regenera do domínio notifications.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-notifications
  system: regenera-bank
