apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-statements
  description: Componente Regenera do domínio statements.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-statements
  system: regenera-bank
