apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-bff-operations
  description: Componente Regenera do domínio operations-bff.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-operations
  system: regenera-bank
