apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-integration-susep
  description: Componente Regenera do domínio susep.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-integration-susep
  system: regenera-bank
