apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-appsec
  description: Componente Regenera do domínio appsec.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-appsec
  system: regenera-bank
