apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-warehouse
  description: Componente Regenera do domínio warehouse.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-warehouse
  system: regenera-bank
