apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-integration-correspondents
  description: Componente Regenera do domínio correspondents.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-integration-correspondents
  system: regenera-bank
