apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-finance-reporting
  description: Componente Regenera do domínio finance-reporting.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-finance-reporting
  system: regenera-bank
