apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-limits
  description: Componente Regenera do domínio limits.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-limits
  system: regenera-bank
