apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-soc
  description: Componente Regenera do domínio soc.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-soc
  system: regenera-bank
