apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-change-management
  description: Componente Regenera do domínio change-management.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-change-management
  system: regenera-bank
