apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-data-lineage
  description: Componente Regenera do domínio lineage.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-data-lineage
  system: regenera-bank
