apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-device-trust
  description: Componente Regenera do domínio device-trust.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-device-trust
  system: regenera-bank
