apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-object-storage
  description: Componente Regenera do domínio object-storage.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-object-storage
  system: regenera-bank
