apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-customer-support
  description: Componente Regenera do domínio customer-support.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-customer-support
  system: regenera-bank
