#!/usr/bin/env node
// 20-verify.mjs
//
// o portão. isto é o que torna seguro soltar um LLM num núcleo bancário.
//
// a regra do agente é: só mexe em comentário.
// este script PROVA isso: tira todo comentário do antes e do depois,
// normaliza espaço, e compara o código byte a byte.
//
// se o agente encostou numa linha executável, o código difere, e reprova.
// não tem "quase". dinheiro não aceita quase.
//
// uso:
//   node tooling/agents/20-verify.mjs <original> <reescrito>
//   echo "<reescrito>" | node tooling/agents/20-verify.mjs <original> -   (lê stdin)
// saída: exit 0 = passou | exit 1 = reprovou (e diz por quê)

import { readFileSync } from 'node:fs';
import { extname } from 'node:path';

const AI_VESTIGES = [
  /REGENERA ENTERPRISE SYSTEM/i,
  /\bAs an AI\b/i,
  /\bGenerated by (?:AI|GPT|Claude|Gemini|Copilot)\b/i,
  /\bv\d+\.\d+\b.*ENTERPRISE/i,
];

// ---------------------------------------------------------------------------
// remoção de comentário ciente de string.
// um `//` dentro de uma string NÃO é comentário. um `--` dentro de aspas no SQL
// também não. se a gente ignorar isso, "remover comentário" corrompe o código
// e o portão vira teatro. então o stripper anda caractere por caractere e sabe
// quando está dentro de string.
// ---------------------------------------------------------------------------

function stripCLike(src) {
  // cobre .ts .tsx .js .mjs .cjs : strings ' " ` , comentários // e /* */
  let out = '';
  let i = 0;
  const n = src.length;
  let str = null; // aspas atual: ' " ou `
  while (i < n) {
    const c = src[i];
    const c2 = src[i + 1];
    if (str) {
      out += c;
      if (c === '\\') { out += c2 ?? ''; i += 2; continue; }
      if (c === str) str = null;
      i += 1;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { str = c; out += c; i += 1; continue; }
    if (c === '/' && c2 === '/') { while (i < n && src[i] !== '\n') i += 1; continue; }
    if (c === '/' && c2 === '*') {
      i += 2;
      while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i += 1;
      i += 2;
      continue;
    }
    out += c;
    i += 1;
  }
  return out;
}

function stripSql(src) {
  // strings '...' (com '' escapado), dollar-quote $tag$...$tag$, comentário -- e /* */
  let out = '';
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    const c2 = src[i + 1];
    if (c === "'") {
      out += c; i += 1;
      while (i < n) {
        out += src[i];
        if (src[i] === "'" && src[i + 1] === "'") { out += src[i + 1]; i += 2; continue; }
        if (src[i] === "'") { i += 1; break; }
        i += 1;
      }
      continue;
    }
    if (c === '$') {
      const m = /^\$[A-Za-z0-9_]*\$/.exec(src.slice(i));
      if (m) {
        const tag = m[0];
        out += tag; i += tag.length;
        const end = src.indexOf(tag, i);
        if (end === -1) { out += src.slice(i); i = n; }
        else { out += src.slice(i, end + tag.length); i = end + tag.length; }
        continue;
      }
    }
    if (c === '-' && c2 === '-') { while (i < n && src[i] !== '\n') i += 1; continue; }
    if (c === '/' && c2 === '*') {
      i += 2;
      while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i += 1;
      i += 2;
      continue;
    }
    out += c; i += 1;
  }
  return out;
}

function stripHashLike(src) {
  // .sh .yml .yaml : comentário '#'. ciente de aspas simples/duplas.
  let out = '';
  let i = 0;
  const n = src.length;
  let str = null;
  while (i < n) {
    const c = src[i];
    if (str) { out += c; if (c === str) str = null; i += 1; continue; }
    if (c === "'" || c === '"') { str = c; out += c; i += 1; continue; }
    if (c === '#') { while (i < n && src[i] !== '\n') i += 1; continue; }
    out += c; i += 1;
  }
  return out;
}

function codeOnly(src, ext) {
  let stripped;
  if (['.ts', '.tsx', '.js', '.mjs', '.cjs'].includes(ext)) stripped = stripCLike(src);
  else if (ext === '.sql') stripped = stripSql(src);
  else if (['.sh', '.yml', '.yaml'].includes(ext)) stripped = stripHashLike(src);
  else stripped = src; // tipo sem stripper: compara cru (markdown, etc.)
  // normaliza espaço: o agente pode ter mudado indentação de comentário, mas o
  // código tem que bater. colapsa whitespace pra comparar só os tokens.
  return stripped.replace(/\s+/g, ' ').trim();
}

function fail(msg) { console.error(`REPROVADO: ${msg}`); process.exit(1); }
function pass(msg) { console.log(`OK: ${msg}`); process.exit(0); }

const [, , origPath, newPath] = process.argv;
if (!origPath || !newPath) {
  console.error('uso: 20-verify.mjs <original> <reescrito|->');
  process.exit(2);
}

const ext = extname(origPath).toLowerCase();
const original = readFileSync(origPath, 'utf8');
const rewritten = newPath === '-' ? readFileSync(0, 'utf8') : readFileSync(newPath, 'utf8');

if (rewritten.trim().length === 0) fail('arquivo reescrito veio vazio.');

// 1) código tem que ser idêntico ignorando comentários
const a = codeOnly(original, ext);
const b = codeOnly(rewritten, ext);
if (a !== b) {
  // acha o primeiro ponto de divergência pra dar pista
  let k = 0;
  while (k < a.length && k < b.length && a[k] === b[k]) k += 1;
  fail(
    `o código mudou (não só comentário). divergência perto de:\n` +
    `  esperado: ...${a.slice(Math.max(0, k - 40), k + 40)}...\n` +
    `  veio:     ...${b.slice(Math.max(0, k - 40), k + 40)}...`,
  );
}

// 2) não pode ter sobrado vestígio de IA
for (const re of AI_VESTIGES) {
  if (re.test(rewritten)) fail(`vestígio de IA permaneceu: ${re}`);
}

// 3) sanidade de chaves (só pra C-like) — não conserta, só alerta cedo
if (['.ts', '.tsx', '.js', '.mjs', '.cjs'].includes(ext)) {
  const code = stripCLike(rewritten);
  const open = (code.match(/\{/g) || []).length;
  const close = (code.match(/\}/g) || []).length;
  if (open !== close) fail(`chaves desbalanceadas após reescrita (${open} vs ${close}).`);
}

pass('código preservado byte a byte; só comentário mudou.');
