#!/usr/bin/env node
// regenera-agente.mjs (Versão 2.0 - Elite Agent)
// ... (cabeçalho mantido) ...

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, extname, relative, resolve } from 'node:path';
import { createInterface } from 'node:readline';

// ===========================================================================
// CONFIGURAÇÕES
// ===========================================================================
const args = process.argv.slice(2);
const flags = new Map();
const pos = [];
for (let i = 0; i < args.length; i += 1) {
  const a = args[i];
  if (a.startsWith('--')) { const k = a.slice(2); const v = args[i + 1]; if (v && !v.startsWith('--')) { flags.set(k, v); i += 1; } else flags.set(k, true); }
  else pos.push(a);
}
const CFG = {
  repo: resolve(pos[0] ?? process.env.REGENERA_REPO ?? '.'),
  url: (flags.get('url') ?? process.env.REGENERA_URL ?? 'http://192.168.1.64:1234/v1').replace(/\/$/, ''),
  model: flags.get('model') ?? process.env.REGENERA_MODEL ?? 'qwen3.5-9b-claude-deckard-agent-coder-heretic-qx86-hi-mlx',
  temperature: Number(flags.get('temp') ?? 0.1), // Reduzido para 0.1 para maior precisão analítica
  maxToolHops: Number(flags.get('max-hops') ?? 8), // Aumentado para permitir análises mais profundas
  maxHistory: 15, // Mantém a memória limpa para não estourar o limite de tokens do LM Studio
  outDir: '.regenera-agent',
};

const EXCLUDE = new Set(['node_modules', '.git', 'dist', 'build', '.next', '.vercel', '__MACOSX', '.regenera-agent']);
const C_LIKE = new Set(['.ts', '.tsx', '.js', '.mjs', '.cjs']);
const GATE_EXT = new Set([...C_LIKE, '.sql', '.sh', '.yml', '.yaml']);
const COL = { dim: (s) => `\x1b[2m${s}\x1b[0m`, cyan: (s) => `\x1b[36m${s}\x1b[0m`, green: (s) => `\x1b[32m${s}\x1b[0m`, red: (s) => `\x1b[31m${s}\x1b[0m`, yellow: (s) => `\x1b[33m${s}\x1b[0m`, bold: (s) => `\x1b[1m${s}\x1b[0m` };

// ===========================================================================
// O PORTÃO + HEURÍSTICA (Intactos pela segurança)
// ===========================================================================
function stripCLike(src) { let o = '', i = 0; const n = src.length; let s = null; while (i < n) { const c = src[i], d = src[i + 1]; if (s) { o += c; if (c === '\\') { o += d ?? ''; i += 2; continue; } if (c === s) s = null; i += 1; continue; } if (c === "'" || c === '"' || c === '`') { s = c; o += c; i += 1; continue; } if (c === '/' && d === '/') { while (i < n && src[i] !== '\n') i += 1; continue; } if (c === '/' && d === '*') { i += 2; while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i += 1; i += 2; continue; } o += c; i += 1; } return o; }
function stripSql(src) { let o = '', i = 0; const n = src.length; while (i < n) { const c = src[i], d = src[i + 1]; if (c === "'") { o += c; i += 1; while (i < n) { o += src[i]; if (src[i] === "'" && src[i + 1] === "'") { o += src[i + 1]; i += 2; continue; } if (src[i] === "'") { i += 1; break; } i += 1; } continue; } if (c === '$') { const m = /^\$[A-Za-z0-9_]*\$/.exec(src.slice(i)); if (m) { const t = m[0]; o += t; i += t.length; const e = src.indexOf(t, i); if (e === -1) { o += src.slice(i); i = n; } else { o += src.slice(i, e + t.length); i = e + t.length; } continue; } } if (c === '-' && d === '-') { while (i < n && src[i] !== '\n') i += 1; continue; } if (c === '/' && d === '*') { i += 2; while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i += 1; i += 2; continue; } o += c; i += 1; } return o; }
function stripHashLike(src) { let o = '', i = 0; const n = src.length; let s = null; while (i < n) { const c = src[i]; if (s) { o += c; if (c === s) s = null; i += 1; continue; } if (c === "'" || c === '"') { s = c; o += c; i += 1; continue; } if (c === '#') { while (i < n && src[i] !== '\n') i += 1; continue; } o += c; i += 1; } return o; }
function codeOnly(src, ext) { let s; if (C_LIKE.has(ext)) s = stripCLike(src); else if (ext === '.sql') s = stripSql(src); else if (['.sh', '.yml', '.yaml'].includes(ext)) s = stripHashLike(src); else s = src; return s.replace(/\s+/g, ' ').trim(); }
const AI_VESTIGES = [/REGENERA ENTERPRISE SYSTEM/i, /\bAs an AI\b/i, /\bGenerated by (?:AI|GPT|Claude|Gemini|Copilot)\b/i, /\bv\d+\.\d+\b.*ENTERPRISE/i];
function gateVerify(orig, rew, ext) { if (rew.trim().length === 0) return { ok: false, reason: 'vazio' }; if (codeOnly(orig, ext) !== codeOnly(rew, ext)) return { ok: false, reason: 'código mudou (não só comentário)' }; for (const re of AI_VESTIGES) if (re.test(rew)) return { ok: false, reason: `vestígio de IA: ${re}` }; if (C_LIKE.has(ext)) { const c = stripCLike(rew); if ((c.match(/\{/g) || []).length !== (c.match(/\}/g) || []).length) return { ok: false, reason: 'chaves desbalanceadas' }; } return { ok: true, reason: 'só comentário mudou' }; }

const DIVIDER = /^\s*\/\/\s*[-=*_]{4,}\s*$/;
const THEATER = /(QUANTUM|CYBERPUNK|\bAGI\b|GOD-?TIER|NEURAL LOGIC ENGINE|ENTERPRISE SYSTEM|SINGULARITY|AI CONTEXT INJECTION|MODEL SELECTION STRATEGY|THEME CONFIG MAPS|RENDERERS)/i;
const LABEL_NOISE = new Set(['components', 'icons', 'extended modules', 'custom hooks', 'ui state', 'settings state', 'notification state', 'navigation state', 'form data', 'form validations', 'email form state', 'email submit handler', 'biometrics scan state', 'raphaela agi state', 'audio refs for gemini tts', 'tts', 'svg dimensions', 'create path', 'type filter', 'category filter', 'global search query', 'sequence timing', 'mouse parallax logic', 'execute', 'parse output', 'extract web intelligence', 'render', 'helpers', 'state', 'styles', 'types']);
function heuristicRewrite(src, ext) {
  if (!C_LIKE.has(ext)) return src.split('\n').filter((l) => !/^\s*[#-]{2}\s*[-=*_]{6,}\s*$/.test(l)).join('\n').replace(/\n{3,}/g, '\n\n');
  let o = '', i = 0; const n = src.length; let s = null;
  const decide = (t) => { const x = t.replace(/\s+$/, ''); const b = x.replace(/^\s*\/\/\s?/, '').trim().toLowerCase(); if (DIVIDER.test(x)) return { drop: 1 }; if (LABEL_NOISE.has(b)) return { drop: 1 }; if (THEATER.test(x)) return { drop: 1 }; return {}; };
  while (i < n) {
    const c = src[i], d = src[i + 1];
    if (s) { o += c; if (c === '\\') { o += d ?? ''; i += 2; continue; } if (c === s) s = null; i += 1; continue; }
    if (c === "'" || c === '"' || c === '`') { s = c; o += c; i += 1; continue; }
    if (c === '/' && d === '/') { let j = i + 2; while (j < n && src[j] !== '\n') j += 1; const cm = src.slice(i, j); let ls = i - 1; while (ls >= 0 && src[ls] !== '\n' && (src[ls] === ' ' || src[ls] === '\t')) ls -= 1; const full = ls < 0 || src[ls] === '\n'; if (decide(cm).drop) { o = o.replace(/[ \t]*$/, ''); i = full && j < n && src[j] === '\n' ? j + 1 : j; continue; } o += cm; i = j; continue; }
    if (c === '/' && d === '*') { let j = i + 2; while (j < n && !(src[j] === '*' && src[j + 1] === '/')) j += 1; j = Math.min(j + 2, n); const bl = src.slice(i, j); let ls = i - 1; while (ls >= 0 && src[ls] !== '\n' && (src[ls] === ' ' || src[ls] === '\t')) ls -= 1; const full = ls < 0 || src[ls] === '\n'; if (/SPDX-License-Identifier|@license/.test(bl)) { o = o.replace(/[ \t]*$/, ''); i = full && j < n && src[j] === '\n' ? j + 1 : j; continue; } o += bl; i = j; continue; }
    o += c; i += 1;
  }
  return o.replace(/\n{3,}/g, '\n\n');
}

// ===========================================================================
// FERRAMENTAS
// ===========================================================================
function walk(dir, acc = []) { for (const e of readdirSync(dir)) { if (EXCLUDE.has(e)) continue; const p = join(dir, e); const st = statSync(p); if (st.isDirectory()) walk(p, acc); else acc.push(p); } return acc; }

function tool_listar_arquivos({ subdir } = {}) {
  const base = subdir ? join(CFG.repo, subdir) : CFG.repo;
  if (!existsSync(base)) return `(Erro: o diretório ${subdir} não existe no repositório.)`;
  const files = walk(base).map((p) => relative(CFG.repo, p)).sort();
  return files.length ? files.join('\n') : '(diretório vazio)';
}
function tool_ler_arquivo({ caminho }) {
  const p = join(CFG.repo, caminho);
  if (!existsSync(p)) return `(Erro: o arquivo ${caminho} não foi encontrado.)`;
  let txt = readFileSync(p, 'utf8');
  if (txt.length > 24000) txt = txt.slice(0, 24000) + `\n... [truncado em 24k chars de ${txt.length} para economizar memória]`;
  return txt;
}
function tool_buscar_no_repo({ termo }) {
  if (!termo) return '(Erro: termo de busca vazio)';
  const re = new RegExp(termo.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
  const hits = [];
  for (const p of walk(CFG.repo)) {
    if (!/\.(ts|tsx|js|cjs|mjs|sql|sh|ya?ml|json|md|html|css)$/i.test(p)) continue;
    try { readFileSync(p, 'utf8').split('\n').forEach((l, i) => { if (re.test(l)) hits.push(`${relative(CFG.repo, p)}:${i + 1}: ${l.trim().slice(0, 120)}`); }); } catch {}
    if (hits.length > 60) break;
  }
  return hits.length ? hits.slice(0, 60).join('\n') : `(Nenhum resultado encontrado para o termo: "${termo}")`;
}
function tool_auditar_seguranca() {
  const SEC = [[/AIza[0-9A-Za-z_\-]{20,}/, 'chave Google API exposta', 'Critical'], [/-----BEGIN [A-Z ]*PRIVATE KEY-----/, 'chave privada embutida', 'Critical'], [/jwt[-_ ]?secret/i, 'JWT secret', 'Critical'], [/(secret|token|password)\s*[:=]\s*['"][^'"]{8,}['"]/i, 'credencial literal', 'High']];
  const out = [];
  for (const p of walk(CFG.repo)) {
    if (!/\.(ts|tsx|js|cjs|mjs|sql|sh|ya?ml|json|html|env)$/i.test(p)) continue;
    try { readFileSync(p, 'utf8').split('\n').forEach((l, i) => { for (const [re, m, sev] of SEC) if (re.test(l)) out.push(`[${sev}] ${relative(CFG.repo, p)}:${i + 1} — ${m}`); if (/\b(TODO|FIXME|HACK)\b/.test(l) && !/@\w+|\(\w+\)|\d{4}-\d{2}-\d{2}/.test(l)) out.push(`[Medium] ${relative(CFG.repo, p)}:${i + 1} — TODO/FIXME órfão`); }); } catch {}
  }
  return out.length ? out.join('\n') : 'Auditoria limpa: nenhum segredo exposto ou TODO órfão encontrado.';
}
function tool_limpar_sinal_ia({ caminho, aplicar } = {}) {
  let targets = walk(CFG.repo).filter((p) => GATE_EXT.has(extname(p).toLowerCase()));
  if (caminho) targets = targets.filter((p) => relative(CFG.repo, p) === caminho || relative(CFG.repo, p).includes(caminho));
  if (targets.length === 0) return `(Erro: arquivo ${caminho} não encontrado ou sem extensão suportada.)`;
  let rew = 0, clean = 0, rej = 0; const lines = [];
  for (const p of targets) {
    const ext = extname(p).toLowerCase(); const orig = readFileSync(p, 'utf8'); const out = heuristicRewrite(orig, ext); const v = gateVerify(orig, out, ext);
    const rel = relative(CFG.repo, p);
    if (!v.ok) { rej += 1; lines.push(`✗ ${rel} (rejeitado: ${v.reason})`); continue; }
    if (out === orig) { clean += 1; continue; }
    rew += 1;
    if (aplicar) writeFileSync(p, out);
    else { const dest = join(CFG.repo, CFG.outDir, 'proposto', rel); mkdirSync(dirname(dest), { recursive: true }); writeFileSync(dest, out); }
    lines.push(`✎ ${rel}`);
  }
  const head = aplicar ? 'APLICADO NO REPOSITÓRIO' : `Modo DRY-RUN (propostas salvas em ${CFG.outDir}/proposto/)`;
  return `${head}\nResumo: reescritos: ${rew} | já limpos: ${clean} | rejeitados: ${rej}\n` + lines.slice(0, 40).join('\n');
}

const TOOLS = [
  { type: 'function', function: { name: 'listar_arquivos', description: 'ÚTIL PARA MAPEAR O PROJETO. Lista caminhos dos arquivos. Use subdir para focar em uma pasta.', parameters: { type: 'object', properties: { subdir: { type: 'string', description: 'subpasta opcional (ex: src/components)' } } } } },
  { type: 'function', function: { name: 'ler_arquivo', description: 'Lê o código-fonte de um arquivo para que você possa entender o que ele faz ou achar problemas.', parameters: { type: 'object', properties: { caminho: { type: 'string' } }, required: ['caminho'] } } },
  { type: 'function', function: { name: 'buscar_no_repo', description: 'Grep no repositório. Use para encontrar onde variáveis, funções ou strings são usadas.', parameters: { type: 'object', properties: { termo: { type: 'string' } }, required: ['termo'] } } },
  { type: 'function', function: { name: 'auditar_seguranca', description: 'Roda uma verificação severa de vazamento de chaves, secrets e TODOs largados no código.', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'limpar_sinal_ia', description: 'Limpa comentários inúteis ou gerados por IA. POR PADRÃO DEVE SER USADO COMO DRY-RUN (aplicar=false). Só passe aplicar=true se o humano ordenou explicitamente.', parameters: { type: 'object', properties: { caminho: { type: 'string', description: 'caminho parcial ou total. vazio = repo inteiro' }, aplicar: { type: 'boolean', description: 'ATENÇÃO: true escreve no disco. false apenas simula.' } } } } },
];
const DISPATCH = { listar_arquivos: tool_listar_arquivos, ler_arquivo: tool_ler_arquivo, buscar_no_repo: tool_buscar_no_repo, auditar_seguranca: tool_auditar_seguranca, limpar_sinal_ia: tool_limpar_sinal_ia };

// ===========================================================================
// LLM - SUPERCHARGED SYSTEM PROMPT
// ===========================================================================

const SYSTEM = `Você é um Arquiteto de Software e Engenheiro de Segurança de Elite de um banco Tier 1.
Você vive dentro deste terminal e governa o repositório em: ${CFG.repo}

SUA DIRETRIZ DE RACIOCÍNIO (Aja de forma rigorosa e cirúrgica):
1. Você TEM FERRAMENTAS REAIS. Nunca adivinhe ou alucine como o código funciona. Se te perguntarem algo sobre o projeto, CHAME as ferramentas 'listar_arquivos', 'buscar_no_repo' e 'ler_arquivo' antes de responder.
2. Seja proativo na investigação. Se o usuário pedir para debugar algo, busque a função no repositório.
3. Seus textos e respostas devem ser extremamente técnicos, diretos, em português do Brasil, estilo "Tech Lead Sênior cansado de código ruim". ZERO enrolação corporativa.
4. Você NUNCA altera código diretamente. O portão de segurança o impede. Você altera apenas comentários usando 'limpar_sinal_ia'.
5. Ao usar ferramentas, interprete os dados recebidos com silêncio, e então entregue a conclusão de forma seca e útil para o humano.`;

async function chatStream(messages, { onToken } = {}) {
  const res = await fetch(`${CFG.url}/chat/completions`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: CFG.model, messages, tools: TOOLS, tool_choice: 'auto', temperature: CFG.temperature, stream: true }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const reader = res.body.getReader(); const dec = new TextDecoder();
  let buf = '', content = ''; const toolAcc = [];
  while (true) {
    const { value, done } = await reader.read(); if (done) break;
    buf += dec.decode(value, { stream: true });
    let nl; while ((nl = buf.indexOf('\n')) >= 0) {
      const line = buf.slice(0, nl).trim(); buf = buf.slice(nl + 1);
      if (!line.startsWith('data:')) continue;
      const payload = line.slice(5).trim(); if (payload === '[DONE]') continue;
      let j; try { j = JSON.parse(payload); } catch { continue; }
      const delta = j.choices?.[0]?.delta ?? {};
      if (delta.content) { content += delta.content; if (onToken) onToken(delta.content); }
      if (delta.tool_calls) for (const tc of delta.tool_calls) { const idx = tc.index ?? 0; toolAcc[idx] ??= { id: tc.id, name: '', args: '' }; if (tc.id) toolAcc[idx].id = tc.id; if (tc.function?.name) toolAcc[idx].name += tc.function.name; if (tc.function?.arguments) toolAcc[idx].args += tc.function.arguments; }
    }
  }
  return { content, tool_calls: toolAcc.filter(Boolean) };
}

// O Otimizador de Memória: Evita que o LM Studio quebre com o limite de tokens
function truncateHistory(messages) {
  if (messages.length <= CFG.maxHistory) return messages;
  const sys = messages[0];
  const tail = messages.slice(-(CFG.maxHistory - 1));
  return [sys, ...tail];
}

async function agentTurn(messages) {
  for (let hop = 0; hop < CFG.maxToolHops; hop += 1) {
    let printedAny = false;
    const safeMessages = truncateHistory(messages);
    const { content, tool_calls } = await chatStream(safeMessages, { onToken: (t) => { if (!printedAny) { process.stdout.write(COL.cyan('\n[Arquiteto]> ')); printedAny = true; } process.stdout.write(t); } });
    
    if (tool_calls.length) {
      messages.push({ role: 'assistant', content: content || null, tool_calls: tool_calls.map((t, i) => ({ id: t.id || `call_${i}`, type: 'function', function: { name: t.name, arguments: t.args || '{}' } })) });
      for (const tc of tool_calls) {
        let argsObj = {}; try { argsObj = JSON.parse(tc.args || '{}'); } catch {}
        process.stdout.write(COL.dim(`\n  ⚙️ Sistema local executando: ${tc.name}(${JSON.stringify(argsObj)})\n`));
        let result; try { result = (DISPATCH[tc.name] ?? (() => `(Erro interno: ferramenta ${tc.name} não existe)`))(argsObj); } catch (e) { result = `(Falha crítica na ferramenta: ${e.message})`; }
        messages.push({ role: 'tool', tool_call_id: tc.id || 'call_0', content: String(result).slice(0, 10000) });
      }
      continue;
    }
    if (printedAny) process.stdout.write('\n\n');
    else process.stdout.write(COL.cyan('\n[Arquiteto]> ') + (content || COL.dim('...')) + '\n\n');
    messages.push({ role: 'assistant', content });
    return;
  }
  process.stdout.write(COL.red('\n[Alerta do Sistema: Agente forçado a parar por limite de ações (looping evitado)]\n\n'));
}

// ===========================================================================
// REPL
// ===========================================================================
async function probeConnection() {
  try { const r = await fetch(`${CFG.url}/models`); const d = await r.json(); const ids = (d?.data ?? []).map((m) => m.id); return { ok: true, ids }; }
  catch (e) { return { ok: false, err: e.message }; }
}

async function main() {
  console.clear();
  console.log(COL.bold('\n  REGENERA V2 · ARQUITETO SÊNIOR LOCAL'));
  console.log(COL.dim(`  Dossiê (Repo): ${CFG.repo}`));
  console.log(COL.dim(`  Motor Lógico:  ${CFG.model}`));
  
  const probe = await probeConnection();
  if (!probe.ok) { console.log(COL.red(`\n  [Erro de Rede] LM Studio não responde em ${CFG.url}`)); process.exit(1); }
  
  console.log(COL.green(`  Sistemas on-line. Modelos ativados: ${probe.ids.join(', ') || '(Nenhum)'}`));
  console.log(COL.dim('  Terminal de comandos rápidos: /limpar | /aplicar | /auditar | /limpartela | /sair\n'));

  const messages = [{ role: 'system', content: SYSTEM }];
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = () => rl.question(COL.bold('Comando> '), handle);

  async function handle(line) {
    const t = line.trim();
    if (!t) return ask();
    if (t === '/sair' || t === '/exit') { console.log(COL.dim('Desconectando.')); rl.close(); return; }
    if (t === '/limpartela') { console.clear(); return ask(); }
    if (t === '/modelo') { console.log(COL.dim(`modelo=${CFG.model}\nendpoint=${CFG.url}\nrepo=${CFG.repo}`)); return ask(); }
    if (t === '/auditar') { console.log(COL.dim('\n⚙️ Executando varredura...\n\n' + tool_auditar_seguranca() + '\n')); return ask(); }
    if (t === '/limpar' || t === '/aplicar') {
      const aplicar = t === '/aplicar';
      console.log(COL.yellow(`\n⚙️ Executando motor de limpeza (${aplicar ? 'GRAVANDO' : 'SIMULAÇÃO'})...`));
      console.log(COL.dim('\n' + tool_limpar_sinal_ia({ aplicar }) + '\n'));
      return ask();
    }
    
    messages.push({ role: 'user', content: t });
    try { await agentTurn(messages); } catch (e) { console.log(COL.red(`\n[Falha Crítica]: ${e.message}\n`)); }
    ask();
  }
  ask();
}

main().catch((e) => { console.error('Erro Fatal:', e.message); process.exit(1); });
