apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-platform-backups
  description: Componente Regenera do domínio backups.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-platform-backups
  system: regenera-bank
