apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-design-documentation
  description: Componente Regenera do domínio design-documentation.
  annotations:
    regenera.io/criticality: medium
spec:
  type: service
  lifecycle: experimental
  owner: team-design-system
  system: regenera-bank
