apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-bff-web
  description: Componente Regenera do domínio web-bff.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-web
  system: regenera-bank
