apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-business-continuity
  description: Componente Regenera do domínio business-continuity.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-business-continuity
  system: regenera-bank
