apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-integration-b3
  description: Componente Regenera do domínio b3.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-integration-b3
  system: regenera-bank
