apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-transactions
  description: Componente Regenera do domínio transactions.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-transactions
  system: regenera-bank
