apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-identity
  description: Componente Regenera do domínio identity.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-identity
  system: regenera-bank
