apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-security-kms-hsm
  description: Componente Regenera do domínio kms-hsm.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-security-kms-hsm
  system: regenera-bank
