apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-tool-release-manifest
  description: Componente Regenera do domínio release-manifest.
  annotations:
    regenera.io/criticality: medium
spec:
  type: service
  lifecycle: experimental
  owner: team-developer-experience
  system: regenera-bank
