apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-core-cards
  description: Componente Regenera do domínio cards.
  annotations:
    regenera.io/criticality: critical
spec:
  type: service
  lifecycle: experimental
  owner: team-cards
  system: regenera-bank
