apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-operations-aml
  description: Componente Regenera do domínio aml.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-operations-aml
  system: regenera-bank
